
paths:
  ROOT_OUT_PATH: './results/'
  ROOT_CHECKPOINT_PATH: './checkpoint/'
  MODELPATH_NORMFLOW: './checkpoint/barc_normflow_pret/rgbddog_v3_model.pt'

optim:
  BATCH_SIZE: 24      

data:
  DATASET: 'ImgCrops' #'stanext24'  # 'ImgCrops'   # 'stanext24'
  VAL_OPT: 'test' 